name: 'Ubuntu '

on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  dynare_6_2_matlab_r2024b_ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2024b
          products: Symbolic_Math_Toolbox Statistics_and_Machine_Learning_Toolbox Optimization_Toolbox Econometrics_Toolbox Parallel_Computing_Toolbox Control_System_Toolbox Global_Optimization_Toolbox
          cache: true

      - name: Rename libraries and fix issues (as in matlab-support package)
        run: |
          if [ -f "/opt/hostedtoolcache/MATLAB/2024.2.999/x64/sys/os/glnxa64/libgcc_s.so.1" ]; then \
              mv /opt/hostedtoolcache/MATLAB/2024.2.999/x64/sys/os/glnxa64/libgcc_s.so.1 /opt/hostedtoolcache/MATLAB/2024.2.999/x64/sys/os/glnxa64/libgcc_s.so.1.bak; \
          fi
          if [ -f "/opt/hostedtoolcache/MATLAB/2024.2.999/x64/sys/os/glnxa64/libstdc++.so.6" ]; then \
              mv /opt/hostedtoolcache/MATLAB/2024.2.999/x64/sys/os/glnxa64/libstdc++.so.6 /opt/hostedtoolcache/MATLAB/2024.2.999/x64/sys/os/glnxa64/libstdc++.so.6.bak; \
          fi
          if [ -f "/opt/hostedtoolcache/MATLAB/2024.2.999/x64/sys/os/glnxa64/libgfortran.so.5" ]; then \
              mv /opt/hostedtoolcache/MATLAB/2024.2.999/x64/sys/os/glnxa64/libgfortran.so.5 /opt/hostedtoolcache/MATLAB/2024.2.999/x64/sys/os/glnxa64/libgfortran.so.5.bak; \
          fi
          if [ -f "/opt/hostedtoolcache/MATLAB/2024.2.999/x64/sys/os/glnxa64/libquadmath.so.0" ]; then \
              mv /opt/hostedtoolcache/MATLAB/2024.2.999/x64/sys/os/glnxa64/libquadmath.so.0 /opt/hostedtoolcache/MATLAB/2024.2.999/x64/sys/os/glnxa64/libquadmath.so.0.bak; \
          fi
          if [ -f "/opt/hostedtoolcache/MATLAB/2024.2.999/x64/bin/glnxa64/libfreetype.so.6" ]; then \
              mv /opt/hostedtoolcache/MATLAB/2024.2.999/x64/bin/glnxa64/libfreetype.so.6 /opt/hostedtoolcache/MATLAB/2024.2.999/x64/bin/glnxa64/libfreetype.so.6.bak; \
          fi
          if [ -f "/opt/hostedtoolcache/MATLAB/2024.2.999/x64/bin/glnxa64/libtiff.so.5" ]; then \
              mv /opt/hostedtoolcache/MATLAB/2024.2.999/x64/bin/glnxa64/libtiff.so.5 /opt/hostedtoolcache/MATLAB/2024.2.999/x64/bin/glnxa64/libtiff.so.5.bak; \
          fi

      - name: Install dependencies for Dynare
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ meson pkgconf python3-pip gfortran \
              libboost-graph-dev libgsl-dev libmatio-dev libslicot-dev libslicot-pic \
              libsuitesparse-dev flex libfl-dev bison texlive texlive-publishers \
              texlive-latex-extra texlive-fonts-extra texlive-font-utils texlive-latex-recommended \
              texlive-science texlive-plain-generic lmodern python3-sphinx tex-gyre latexmk \
              libjs-mathjax x13as liboctave-dev octave-control octave-econometrics octave-io \
              octave-statistics octave-struct octave-parallel gnuplot fonts-freefont-otf \
              ghostscript epstool git git-lfs

      - name: Compile Dynare
        run: |
          export GIT_CLONE_PROTECTION_ACTIVE=false
          git clone --depth 1 --branch 6.2 --recurse-submodules https://git.dynare.org/dynare/dynare.git
          cd dynare
          pip3 install meson==1.3.1
          export PATH="/home/matlab/.local/bin:${PATH}"
          meson setup -Dmatlab_path=/opt/hostedtoolcache/MATLAB/2024.2.999/x64 -Dbuildtype=debugoptimized build-matlab
          meson compile -C build-matlab
          cd ..

      - name: Run week 1 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("dynare/matlab");
            cd("progs/matlab");
            quickTourMatlab;

      - name: Run week 2 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("dynare/matlab");
            cd("progs/matlab");
            visualizingTimeSeriesDataNorway;
            definitionFrequenciesTimeSeriesData;
            whiteNoisePlots;
            plotsAR1;

      - name: Run week 3 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("dynare/matlab");
            cd("progs/matlab");
            acfPlots_run;
            lawOfLargeNumbers;
            lawOfLargeNumbersAR1;
            centralLimitDependentData;

      - name: Run week 4 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("dynare/matlab");
            cd("progs/matlab");
            AR4OLS;
            AR4ML;
            AR1MLLaplace;

      - name: Run week 5 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("dynare/matlab");
            cd("progs/matlab");
            AR4LagSelection;
            portmanteauTest;
            bootstrapCIAR1;

      - name: Run week 6 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("dynare/matlab");
            cd("progs/matlab");
            matrixAlgebraEigenvalues;
            matrixAlgebraKroneckerFormula;
            matrixAlgebraRotation;
            matrixAlgebraCholesky;
            matrixAlgebraLyapunovComparison;
            VARpDimensionsIllustration;
            threeVariableVAROLS;
            threeVariableVARML;

      - name: Run week 7 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("dynare/matlab");
            cd("progs/matlab");
            USOil;

      - name: Run week 9 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("dynare/matlab");
            cd("progs/matlab");
            keatingSR;
            BlanchardQuahLR;

      - name: Run week 10 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("dynare/matlab");
            cd("progs/matlab");
            RWZSRLR;
            bootstrappingStdIRFs_RWZSRLR;

      - name: Run week 11 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("dynare/matlab");
            cd("progs/matlab");
            BayesianQuarterlyInflation;

      - name: Run week 12 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("dynare/matlab");
            cd("progs/matlab");
            BVARZLB_run;

      - name: Run week 13 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("dynare/matlab");
            cd("progs/matlab");
            rbcLogutilSSTest;
            rbcSSTest;
            cd("../dynare");
            dynare rbcLogutil
            dynare rbcCES