name: 'macOS '

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dynare_6_2_matlab_r2024b_macos:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2024b
          products: Symbolic_Math_Toolbox Statistics_and_Machine_Learning_Toolbox Optimization_Toolbox Econometrics_Toolbox Parallel_Computing_Toolbox Control_System_Toolbox Global_Optimization_Toolbox
          cache: true

      - name: Download Dynare .pkg for macOS ARM64
        run: |          
          curl -L "https://www.dynare.org/release/macos-arm64/dynare-6.2-arm64.pkg" -o "dynare-6.2-arm64.pkg"
        shell: bash

      - name: Install Dynare from the .pkg file (without sudo)
        run: |
          pkgutil --expand dynare-6.2-arm64.pkg Dynare-6.2-arm64
          cd Dynare-6.2-arm64/dynare-6.2-arm64.pkg/
          tar -zxvf Payload -C ../
          ls
          cd ..
          cd ..
        shell: bash

      - name: Run week 1 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("Dynare-6.2-arm64/matlab");
            cd("progs/matlab");
            quickTourMatlab;

      - name: Run week 2 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("Dynare-6.2-arm64/matlab");
            cd("progs/matlab");
            visualizingTimeSeriesDataNorway;
            definitionFrequenciesTimeSeriesData;
            whiteNoisePlots;
            plotsAR1;

      - name: Run week 3 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("Dynare-6.2-arm64/matlab");
            cd("progs/matlab");
            acfPlots_run;
            lawOfLargeNumbers;
            lawOfLargeNumbersAR1;
            centralLimitDependentData;

      - name: Run week 4 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("Dynare-6.2-arm64/matlab");
            cd("progs/matlab");
            AR4OLS;
            AR4ML;
            AR1MLLaplace;

      - name: Run week 5 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("Dynare-6.2-arm64/matlab");
            cd("progs/matlab");
            AR4LagSelection;
            portmanteauTest;
            bootstrapCIAR1;

      - name: Run week 6 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("Dynare-6.2-arm64/matlab");
            cd("progs/matlab");
            matrixAlgebraEigenvalues;
            matrixAlgebraKroneckerFormula;
            matrixAlgebraRotation;
            matrixAlgebraCholesky;
            matrixAlgebraLyapunovComparison;
            VARpDimensionsIllustration;
            threeVariableVAROLS;
            threeVariableVARML;

      - name: Run week 7 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("Dynare-6.2-arm64/matlab");
            cd("progs/matlab");
            USOil;

      - name: Run week 9 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("Dynare-6.2-arm64/matlab");
            cd("progs/matlab");
            keatingSR;
            BlanchardQuahLR;

      - name: Run week 10 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("Dynare-6.2-arm64/matlab");
            cd("progs/matlab");
            RWZSRLR;
            bootstrappingStdIRFs_RWZSRLR;

      - name: Run week 11 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("Dynare-6.2-arm64/matlab");
            cd("progs/matlab");
            BayesianQuarterlyInflation;

      - name: Run week 12 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("Dynare-6.2-arm64/matlab");
            cd("progs/matlab");
            BVARZLB_run;